// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO Feeds (id, createdAt, updatedAt, name, url, user_id, FeedQuantity, processed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, createdat, updatedat, name, url, user_id, feedquantity, processed
`

type CreateFeedParams struct {
	ID           uuid.UUID
	Createdat    time.Time
	Updatedat    time.Time
	Name         string
	Url          string
	UserID       uuid.UUID
	Feedquantity int32
	Processed    bool
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Createdat,
		arg.Updatedat,
		arg.Name,
		arg.Url,
		arg.UserID,
		arg.Feedquantity,
		arg.Processed,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.Feedquantity,
		&i.Processed,
	)
	return i, err
}

const feedsWithoutProcess = `-- name: FeedsWithoutProcess :many
SELECT id, createdat, updatedat, name, url, user_id, feedquantity, processed FROM Feeds where processed=False
`

func (q *Queries) FeedsWithoutProcess(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, feedsWithoutProcess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.Updatedat,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.Feedquantity,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFeeds = `-- name: GetAllFeeds :many
SELECT id, createdat, updatedat, name, url, user_id, feedquantity, processed FROM Feeds ORDER BY createdAt desc
`

func (q *Queries) GetAllFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.Updatedat,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.Feedquantity,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecificFeed = `-- name: GetSpecificFeed :one
SELECT id, createdat, updatedat, name, url, user_id, feedquantity, processed FROM Feeds where id=$1
`

func (q *Queries) GetSpecificFeed(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getSpecificFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.Feedquantity,
		&i.Processed,
	)
	return i, err
}

const getUserFeeds = `-- name: GetUserFeeds :many
SELECT id, createdat, updatedat, name, url, user_id, feedquantity, processed FROM feeds WHERE user_id=$1 ORDER BY createdAt desc
`

func (q *Queries) GetUserFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.Updatedat,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.Feedquantity,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedProcessed = `-- name: MarkFeedProcessed :one
UPDATE feeds
SET processed = true,
    updatedAt = NOW()
WHERE id = $1
    RETURNING id, createdat, updatedat, name, url, user_id, feedquantity, processed
`

func (q *Queries) MarkFeedProcessed(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedProcessed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.Feedquantity,
		&i.Processed,
	)
	return i, err
}
