// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follow.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one

INSERT INTO FeedFollows (id, createdAt, updatedAt, user_id, feed_id, lastFetchedAt)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, createdat, updatedat, user_id, feed_id, lastfetchedat
`

type CreateFeedFollowParams struct {
	ID            uuid.UUID
	Createdat     time.Time
	Updatedat     time.Time
	UserID        uuid.UUID
	FeedID        uuid.UUID
	Lastfetchedat time.Time
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (Feedfollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.Createdat,
		arg.Updatedat,
		arg.UserID,
		arg.FeedID,
		arg.Lastfetchedat,
	)
	var i Feedfollow
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.UserID,
		&i.FeedID,
		&i.Lastfetchedat,
	)
	return i, err
}

const listAllFeedPosts = `-- name: ListAllFeedPosts :many
SELECT p.id, p.title, p.description, p.publishedat, p.link, p.feedid
FROM posts p
         INNER JOIN feeds f ON f.id = p.feedid
         INNER JOIN feedfollows ff ON ff.feed_id = f.id
WHERE ff.user_id = $1
`

func (q *Queries) ListAllFeedPosts(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listAllFeedPosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Publishedat,
			&i.Link,
			&i.Feedid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
