// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follow.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one

INSERT INTO FeedFollows (id, createdAt, updatedAt, user_id, feed_id, lastFetchedAt)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, createdat, updatedat, user_id, feed_id, lastfetchedat
`

type CreateFeedFollowParams struct {
	ID            uuid.UUID
	Createdat     time.Time
	Updatedat     time.Time
	UserID        uuid.UUID
	FeedID        uuid.UUID
	Lastfetchedat time.Time
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (Feedfollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.Createdat,
		arg.Updatedat,
		arg.UserID,
		arg.FeedID,
		arg.Lastfetchedat,
	)
	var i Feedfollow
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.UserID,
		&i.FeedID,
		&i.Lastfetchedat,
	)
	return i, err
}
